site_name: Sapienza Technology Team
site_url: https://sapienza-technology.github.io/documentation/
theme:
  name: material
  features:
    - navigation.tabs  # Menu orizzontale figo
    - search.suggest
markdown_extensions:
  - pymdownx.superfences # Per Mermaid
  - admonition  
